#!/usr/bin/env node
/**
 * Codegen — scans souls/<name>/SOUL.md and emits
 * src/lib/souls/registry.generated.ts with an allowlist and frontmatter meta.
 *
 * Parallels scripts/gen-skills.mjs. Runs via predev/prebuild/postinstall.
 */

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const soulsDir = join(repoRoot, "souls");
const outPath = join(repoRoot, "src", "lib", "souls", "registry.generated.ts");

const PERSONA_NAME_RE = /^[a-z][a-z0-9-]{0,63}$/;

async function scan() {
  const entries = await readdir(soulsDir, { withFileTypes: true }).catch(() => []);
  const souls = [];
  for (const ent of entries) {
    if (!ent.isDirectory()) continue;
    if (!PERSONA_NAME_RE.test(ent.name)) {
      throw new Error(`[gen-souls] invalid persona name "${ent.name}" — must match ${PERSONA_NAME_RE}`);
    }

    const soulMdPath = join(soulsDir, ent.name, "SOUL.md");
    const raw = await readFile(soulMdPath, "utf-8").catch(() => null);
    if (!raw) {
      console.warn(`[gen-souls] skip ${ent.name} — no SOUL.md`);
      continue;
    }

    const { data } = matter(raw);
    if (data.name && data.name !== ent.name) {
      throw new Error(
        `[gen-souls] ${ent.name}/SOUL.md frontmatter name "${data.name}" must match directory name`,
      );
    }
    if (!data.description) {
      throw new Error(`[gen-souls] ${ent.name}/SOUL.md frontmatter missing "description"`);
    }

    souls.push({
      dirName: ent.name,
      description: String(data.description),
      version: data.version != null ? Number(data.version) : 1,
    });
  }
  souls.sort((a, b) => a.dirName.localeCompare(b.dirName));

  if (!souls.find((s) => s.dirName === "default")) {
    throw new Error(`[gen-souls] souls/default/SOUL.md is required (fallback persona)`);
  }
  return souls;
}

function render(souls) {
  const names = souls.map((s) => JSON.stringify(s.dirName)).join(", ");
  const unionType = souls.map((s) => JSON.stringify(s.dirName)).join(" | ");
  const metaEntries = souls
    .map(
      (s) =>
        `  ${JSON.stringify(s.dirName)}: { description: ${JSON.stringify(s.description)}, version: ${s.version} },`,
    )
    .join("\n");

  return `// AUTO-GENERATED by scripts/gen-souls.mjs — DO NOT EDIT
// Run \`npm run gen:souls\` (or predev/prebuild) to regenerate.

export const PERSONAS = [${names}] as const;

export type PersonaName = ${unionType};

export interface PersonaMeta {
  description: string;
  version: number;
}

export const PERSONA_META: Record<PersonaName, PersonaMeta> = {
${metaEntries}
};
`;
}

async function main() {
  const souls = await scan();
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, render(souls), "utf-8");
  console.log(`[gen-souls] wrote ${souls.length} soul(s) → ${relative(repoRoot, outPath)}`);
  for (const s of souls) console.log(`  - ${s.dirName} (v${s.version})`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
