#!/usr/bin/env node
/**
 * Codegen — scans skills/<name>/SKILL.md + handler.ts
 * and emits src/lib/skills/registry.generated.ts with static imports.
 *
 * Must run before `next dev` / `next build` (wired via predev/prebuild).
 */

import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const skillsDir = join(repoRoot, "skills");
const outPath = join(repoRoot, "src", "lib", "skills", "registry.generated.ts");

function sanitizeIdent(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

async function scan() {
  const entries = await readdir(skillsDir, { withFileTypes: true }).catch(() => []);
  const skills = [];
  for (const ent of entries) {
    if (!ent.isDirectory()) continue;
    const dir = join(skillsDir, ent.name);
    const skillMdPath = join(dir, "SKILL.md");
    const handlerTsPath = join(dir, "handler.ts");

    const raw = await readFile(skillMdPath, "utf-8").catch(() => null);
    if (!raw) {
      console.warn(`[gen-skills] skip ${ent.name} — no SKILL.md`);
      continue;
    }
    await stat(handlerTsPath).catch(() => {
      throw new Error(`[gen-skills] ${ent.name}: SKILL.md found but handler.ts missing`);
    });

    const { data } = matter(raw);
    const required = ["name", "description", "input_schema"];
    for (const k of required) {
      if (!(k in data)) throw new Error(`[gen-skills] ${ent.name}: SKILL.md frontmatter missing "${k}"`);
    }

    skills.push({
      dirName: ent.name,
      name: data.name,
      description: data.description,
      input_schema: data.input_schema,
      handlerImportPath: toPosix(relative(dirname(outPath), handlerTsPath).replace(/\.ts$/, "")),
    });
  }
  return skills;
}

function toPosix(p) {
  return p.split(/[\\/]/).join("/").replace(/^(?!\.)/, "./");
}

function render(skills) {
  const imports = skills
    .map((s) => `import { execute as ${sanitizeIdent(s.name)}_execute } from "${s.handlerImportPath}";`)
    .join("\n");

  const tools = skills
    .map(
      (s) =>
        `  {\n    name: ${JSON.stringify(s.name)},\n    description: ${JSON.stringify(s.description)},\n    input_schema: ${JSON.stringify(s.input_schema, null, 2).replace(/\n/g, "\n    ")},\n  },`,
    )
    .join("\n");

  const executors = skills
    .map((s) => `  ${JSON.stringify(s.name)}: ${sanitizeIdent(s.name)}_execute as (args: unknown) => Promise<string>,`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/gen-skills.mjs — DO NOT EDIT
// Run \`npm run gen:skills\` (or predev/prebuild) to regenerate.

import type { ToolDef } from "../llm/types";

${imports}

export const tools: readonly ToolDef[] = [
${tools}
] as const;

export const executors: Record<string, (args: unknown) => Promise<string>> = {
${executors}
};
`;
}

async function main() {
  const skills = await scan();
  await mkdir(dirname(outPath), { recursive: true });
  const content = render(skills);
  await writeFile(outPath, content, "utf-8");
  console.log(`[gen-skills] wrote ${skills.length} skill(s) → ${relative(repoRoot, outPath)}`);
  for (const s of skills) console.log(`  - ${s.name}  (${s.dirName}/)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});