/**
 * Smoke: memory_search skill end-to-end via executeSkill().
 *
 * Assumes AGENT_MEMORY_DIR is set and at least one episode exists there. For
 * the first real session the repo should contain
 *   episodes/2026-04-17-cia-...-e17324.md
 * generated by scripts/consolidate.ts.
 */

import { executeSkill } from "../src/lib/skills/loader";

interface SearchResponse {
  error?: string;
  query?: string;
  count?: number;
  results?: Array<{
    id: string;
    title: string;
    outcome: string;
    score: number;
    matched: string[];
  }>;
}

function parse(output: string): SearchResponse {
  return JSON.parse(output) as SearchResponse;
}

function assert(cond: unknown, msg: string) {
  if (!cond) {
    console.error(`[FAIL] ${msg}`);
    process.exit(1);
  }
}

async function main() {
  if (!process.env.AGENT_MEMORY_DIR) {
    console.error("AGENT_MEMORY_DIR must be set for this smoke");
    process.exit(2);
  }

  const r1 = parse(await executeSkill("memory_search", { query: "CIA 토큰", limit: 3 }));
  console.log("[q1] CIA 토큰 →", JSON.stringify(r1, null, 2).slice(0, 400));
  assert(typeof r1.count === "number", "count field missing");
  assert((r1.count ?? 0) >= 1, "expected at least 1 hit for 'CIA 토큰'");
  assert(Array.isArray(r1.results), "results not an array");
  assert(r1.results![0]!.matched.length > 0, "no matched tokens");
  console.log(`[ok]   'CIA 토큰' → ${r1.count} hit(s), top score=${r1.results![0]!.score}`);

  const r2 = parse(await executeSkill("memory_search", { query: "compare_mode", limit: 2 }));
  assert((r2.count ?? 0) >= 1, "expected hit for 'compare_mode'");
  console.log(`[ok]   'compare_mode' → ${r2.count} hit(s)`);

  const r3 = parse(await executeSkill("memory_search", { query: "zzz-nonexistent-xxx" }));
  assert(r3.count === 0, `expected 0 hits for nonsense, got ${r3.count}`);
  console.log(`[ok]   nonsense query → 0 hits`);

  const r4 = parse(await executeSkill("memory_search", {
    query: "CIA",
    outcome: "failed",
  }));
  assert(r4.count === 0, `expected 0 hits with outcome=failed (only resolved exists), got ${r4.count}`);
  console.log(`[ok]   outcome filter excludes non-matching`);

  const r5 = parse(await executeSkill("memory_search", { query: "" }));
  assert(r5.error === "invalid_query", "empty query should error");
  console.log(`[ok]   empty query → invalid_query`);

  console.log("\nmemory_search smoke passed.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
